; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = ; Uncomment adequate script down below and comment the other
    ;post:post_upload_manual.py  ; auto-launch manual_logger.py after upload
    post:post_upload_sweep.py ; auto-launch sweep.py after upload

lib_deps =
    bogde/HX711
    madhephaestus/ESP32Servo

[env:uno]
platform = atmelavr
board = uno
framework = arduino

lib_deps =
    arduino-libraries/Servo
    bogde/HX711
